### ISSUE TITLE
DB columns for TaskService are to small

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#447]
The attributes column `value` of `plf_task_payload_attributes` ist with maximal 255 chars to small to import some tasks.

**Comment by zambrovski** [comment]
The name of the property is 255 characters long?

**Comment by simonhir** [comment]
No the value

**Comment by darenegade** [comment]
Solution: Increase Size of the following Coloumns: 

* plf_task_description 
* plf_task_name

Size should follow Engine Size

**Comment by darenegade** [comment]
`plf_task_payload_attributes` -> `Value` should be `text`

https://github.com/it-at-m/digiwf-core/blob/7b1ffab6fa494a7ed6eb7a7ad2e5bd7954e21dbd/digiwf-task/digiwf-tasklist-service/src/main/resources/db/migration/postgresql/V02__jpa_view.sql#L126

**Comment by darenegade** [comment]
`plf_task_payload_attributes` -> `Value` should be `text`

https://github.com/it-at-m/digiwf-core/blob/7b1ffab6fa494a7ed6eb7a7ad2e5bd7954e21dbd/digiwf-task/digiwf-tasklist-service/src/main/resources/db/migration/postgresql/V02__jpa_view.sql#L126

**Comment by darenegade** [comment]
As the Index grows with the size of the values, we should define an include list for special attributes only:

https://www.holunda.io/camunda-bpm-taskpool/3.1.1/reference-guide/components/view-jpa.html

**Comment by zambrovski** [comment]
As @darenegade wrote we should not change anything in DB because:
- it makes no sense to index payload attributes of a task if it is not used for the search (currently it is not used)
- if no search based on payload is executed, we should disable indexing (and use of `plf_task_attributes` entirely)
- the size of `plf_task.description` is already 2048 chars which is big enough to store the value of the task description.
